// eslint-config-next 16 ships native flat config, so it is spread directly.
// It must not go back through `FlatCompat`: the compat shim exists to translate
// eslintrc-format config, and wrapping an already-flat config in it makes the
// validator serialise a structure that refers to itself - `TypeError: Converting
// circular structure to JSON`, at load, before a single file is linted.
import nextCoreWebVitals from "eslint-config-next/core-web-vitals";
import nextTypeScript from "eslint-config-next/typescript";

const eslintConfig = [
  // Without these, `eslint .` walks build output and agent scratch directories
  // and reports tens of thousands of problems in generated code, which makes
  // `pnpm lint` useless. Present since the initial commit.
  {
    ignores: [
      ".next/**",
      "supabase/.temp/**",
      ".claude/**",
      "next-env.d.ts",
      "lib/database.types.ts", // generated by `supabase gen types`
    ],
  },
  ...nextCoreWebVitals,
  ...nextTypeScript,
];

export default eslintConfig;
