import { dirname } from "path";
import { fileURLToPath } from "url";
import { FlatCompat } from "@eslint/eslintrc";

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

const compat = new FlatCompat({
  baseDirectory: __dirname,
});

const eslintConfig = [
  // Without these, `eslint .` walks build output and agent scratch directories
  // and reports tens of thousands of problems in generated code, which makes
  // `pnpm lint` useless. Present since the initial commit.
  {
    ignores: [
      ".next/**",
      "supabase/.temp/**",
      ".claude/**",
      "next-env.d.ts",
      "lib/database.types.ts", // generated by `supabase gen types`
    ],
  },
  ...compat.extends("next/core-web-vitals", "next/typescript"),
];

export default eslintConfig;
